<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" Sdk="Microsoft.NET.Sdk">
  <Target Name="Default" />
  <PropertyGroup>
    <AssemblyName>ExcelFast</AssemblyName>
    <RootNamespace>ExcelFast.PowerShell</RootNamespace>
    <TargetFrameworks>net8.0;net472</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup Label="BuildOptions">
    <DebugType>portable</DebugType>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <PublishDir>$(ArtifactsPath)/Module</PublishDir>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup Label="Dependencies">
    <PackageReference Include="Roslynator.Analyzers" Version="4.13.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
		<PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="SixLabors.Fonts" Version="1.0.1" />
		<PackageReference Include="MiniExcel" Version="1.43.1" />

    <!--
    Allows us to reference any type in our ALCLoader.Shared assembly. This can
    provide a common set of classes we can exchange with PowerShell as it's
    loaded in the default AppDomain.
    -->
    <ProjectReference Include="../ALCLoader/ALCLoader.csproj" />
  </ItemGroup>



  <ItemGroup Label="PSCore" Condition=" '$(TargetFramework)' == 'net8.0' ">
    <PackageReference Include="System.Management.Automation" Version="7.4.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup Label="PSDesktop" Condition="'$(TargetFramework)' == 'net472' ">
    <PackageReference Include="PowerShellStandard.Library" Version="5.1.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="PolySharp" Version="1.15.0" />
    <PackageReference Include="Microsoft.BCL.AsyncInterfaces" Version="10.0.0" />
  </ItemGroup>

  <!-- <Target Name="CopyPsdAssets" AfterTargets="Publish">
    <Copy SourceFiles="ExcelFast.psd1" DestinationFolder="$(PublishDir)" />
    <Copy SourceFiles="ExcelFast.Init.ps1" DestinationFolder="$(PublishDir)" />
    <CreateItem Include="Formats\*.ps1xml">
      <Output TaskParameter="Include" ItemName="FormatFiles" />
    </CreateItem>
    <Copy SourceFiles="@(FormatFiles)" DestinationFolder="$(PublishDir)\Formats" />
    <Copy SourceFiles="../../LICENSE.MD" DestinationFolder="$(PublishDir)" />
    <Copy SourceFiles="../../README.MD" DestinationFolder="$(PublishDir)" />
    <Copy SourceFiles="../../Docs/about_ExcelFast.help.txt" DestinationFolder="$(PublishDir)\en-US" />
    <Copy SourceFiles="../../THIRD-PARTY-NOTICES.TXT" DestinationFolder="$(PublishDir)" />
  </Target> -->
</Project>