name: ♻️ ExcelFast CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'
  pull_request:
    branches: [ main, ci ]

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: 👷 Build
    runs-on: windows-2025
    outputs:
      nupkg_artifact_id: ${{ steps.upload_nupkg.outputs.artifact-id }}
    steps:
    - name: 🚚 Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0 # Required for GitVersion
    - name: ⚡ Cache NuGet packages
      uses: actions/cache@v5
      with:
        path: |
          ~/.nuget/packages
          ~/.local/share/powershell/Modules
          Artifacts
          !Artifacts/Module
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: ⚡ Install PowerShell Modules
      uses: JustinGrote/ModuleFast-action@v0.0.1
      with:
        update: true
    - name: 👷 Build
      env:
        # "Pin" the module version if the workflow is triggered by a tag
        MODULEVERSION: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || null }}
      run: |
        try {Invoke-Build}
        catch {
          "::error file=$PSScriptRoot/build.ps1::Build failed with error: $($_.Exception.Message) `n $(Get-Error | Out-String)" -replace "`n","%0A"
          throw
        }
    - name: 🧪 Test
      run: |
        try {Invoke-Build Pester}
        catch {
          "::error file=$PSScriptRoot/build.ps1::Build failed with error: $($_.Exception.Message) `n $(Get-Error | Out-String)" -replace "`n","%0A"
          throw
        }
    - name: 🧪 Test - WinPS
      run: |
        try {Invoke-Build Pester-WinPS}
        catch {
          "::error file=$PSScriptRoot/build.ps1::Build failed with error: $($_.Exception.Message) `n $(Get-Error | Out-String)" -replace "`n","%0A"
          throw
        }
    - name: 📤 Upload Module Zip
      uses: actions/upload-artifact@v7
      with:
        name: ExcelFast
        path: ./Artifacts/Module
    - name: 📤 Upload Nupkg
      id: upload_nupkg
      uses: actions/upload-artifact@v7
      with:
        name: ExcelFast-nupkg
        path: ./Artifacts/*.nupkg
        archive: false #Get nupkg directly

  publish:
    name: 🚢 Publish to PowerShell Gallery
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    environment:
      name: PowerShell Gallery
      url: https://www.powershellgallery.com/packages/ExcelFast
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Download Build Artifacts
      uses: actions/download-artifact@v8
      with:
        artifact-ids: ${{ needs.build.outputs.nupkg_artifact_id }}
        path: ./Release
    - name: 🚢 Publish to PowerShell Gallery
      env:
        PSGALLERY_API_KEY: ${{ secrets.PSGALLERY }}
      run: |
        $DebugPreference = 'Continue'
        $VerbosePreference = 'Continue'

        $nupkg = Get-ChildItem -Path ./Release/*.nupkg
        if ($nupkg.Count -eq 0)
        {
          throw "No nupkg found in Release directory"
        }
        elseif ($nupkg.Count -gt 1)
        {
          throw "Multiple nupkg files found in Release directory: $($nupkg.FullName -join ', ')"
        }

        # Bugfix for PSResourceRepository not being registered in GitHub Actions environment
        Register-PSResourceRepository -PSGallery -Force

        Publish-PSResource -Nupkg $nupkg.FullName -ApiKey $env:PSGALLERY_API_KEY